# Generated by Django 2.2.3 on 2019-07-29 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import occurrence.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[(occurrence.models.State('not validated'), 'not validated'), (occurrence.models.State('validated'), 'validated'), (occurrence.models.State('resolved'), 'resolved')], max_length=13)),
                ('category', models.CharField(choices=[(occurrence.models.Category('planned road work'), 'planned road work'), (occurrence.models.Category('special events (fair, sport event, etc.)'), 'special events (fair, sport event, etc.)'), (occurrence.models.Category('accidents and other unexpected events'), 'accidents and other unexpected events'), (occurrence.models.Category('weather condition affecting the road'), 'weather condition affecting the road'), (occurrence.models.Category('status of the road that might affect travellers     (potholes, bad pavement, etc)'), 'status of the road that might affect travellers     (potholes, bad pavement, etc)')], max_length=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
